# Generated by Django 5.2.15 on 2026-06-19 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Angler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('favorite_fish', models.CharField(blank=True, max_length=100, verbose_name='Любимая рыба')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='angler', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рыболов',
                'verbose_name_plural': 'Рыболовы',
            },
        ),
        migrations.CreateModel(
            name='FishingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('spot_type', models.CharField(choices=[('lake', 'Озеро'), ('river', 'Река'), ('pond', 'Пруд'), ('reservoir', 'Водохранилище'), ('sea', 'Море')], max_length=20, verbose_name='Тип водоёма')),
                ('target_fish', models.CharField(blank=True, max_length=100, verbose_name='Целевая рыба')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('angler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='diary.angler', verbose_name='Рыболов')),
            ],
            options={
                'verbose_name': 'Водоём',
                'verbose_name_plural': 'Водоёмы',
            },
        ),
        migrations.CreateModel(
            name='FishingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('water_temp', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Температура воды (°C)')),
                ('pressure', models.PositiveIntegerField(verbose_name='Давление (мм рт. ст.)')),
                ('moon_phase', models.CharField(choices=[('new', 'Новолуние'), ('waxing', 'Растущая'), ('full', 'Полнолуние'), ('waning', 'Убывающая')], max_length=20, verbose_name='Фаза луны')),
                ('catch_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Вес улова (кг)')),
                ('fish_species', models.CharField(blank=True, max_length=100, verbose_name='Виды рыбы')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('angler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='diary.angler', verbose_name='Рыболов')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='diary.fishingspot', verbose_name='Водоём')),
            ],
            options={
                'verbose_name': 'Выезд',
                'verbose_name_plural': 'Выезды',
                'ordering': ['-date'],
            },
        ),
    ]
